<?php

namespace AppBundle\Repository;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends \Doctrine\ORM\EntityRepository
{
}
