<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Form;

/**
 * ValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find values by a form
     *
     * @param Form $form
     * @return array
     */
    public function findValuesByForm(Form $form)
    {
        $qb = $this->createQueryBuilder("v");
        $qb ->where($qb->expr()->eq('v.form', $form->getId()));
        return $qb->getQuery()->getResult();
    }
}
