---
- name: Add ppa Repository (nodejs)
  sudo: yes
  apt_repository: repo=ppa:chris-lea/node.js update_cache=yes

- name: Install nodejs Packages
  sudo: yes
  apt: pkg=nodejs state=present

- name: Update nodejs
  sudo: yes
  shell: npm cache clean -f && npm install -g n && n stable
